### PR TITLE
AB#ImplementAzureADAuthenticationAndApplyToUpdateAction

### PR DESCRIPTION
**Pull request by zakiahmed-worldvision**

### CODE REVIEW

**Review by geethakrishnamoorthy — CHANGES_REQUESTED** [review]
Azure AD Function is not working correctly. 
Displaying Featureswitch dashboard application without login. Should show login page if we did not log in or application launch

**Comment by zakiahmed-worldvision** [comment]
Hi Geetha, I have tested it and it is definitely working.

**Comment by zakiahmed-worldvision** [comment]
Hi Geetha, just to clarify. The story did not mention anything about, **currently** authorising the actual (dashboard) page, **only the "Update" function**. There is no other page apart from the FeatureSwitch Dashboard page.

**Comment by geethakrishnamoorthy** [comment]
> Hi Geetha, just to clarify. The story did not mention anything about, **currently** authorizing the actual (dashboard) page, **only the "Update" function**. There is no other page apart from the FeatureSwitch Dashboard page.

As Discussed with Nick, 
1) Azure AD Authentication should implement for the whole dashboard application.  If you login via an azure ad, then only you able to see that dashboard page.
2) If you are an admin user, then only you able to update the feature status. 
3) If other users, you able to all other operations except the update process.

**Comment by zakiahmed-worldvision** [comment]
1) Removed [AllowAnonymous] attribute tag from index. All users must now login to see the Dashboard.
2) Please test with the already provided accounts
3) Please test with the already provided accounts

Admin User: testAdmin@featureswitchdashboard.onmicrosoft.com 
Password: Worldvision12

Non-Admin User: testunauthorised@featureswitchdashboard.onmicrosoft.com
Password: Worldvision12

**Comment by geethakrishnamoorthy** [comment]
Verified

**Pull request merged**
